/*
 * File: st_deliverables.js
 * Date: Mon Oct 18 2010 18:27:13 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

st_deliverables = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        st_deliverables.superclass.constructor.call(this, Ext.apply({
            storeId: 'st_deliverables',
            root: 'data',
            url: 'http://localhost:8000/api/deliverables/12345/?format=ext-json',
            autoLoad: true,
            fields: [
                {
                    name: 'description',
                    mapping: 'description'
                },
                {
                    name: 'pk',
                    mapping: 'id'
                },
                {
                    name: 'acceptance_criteria',
                    mapping: 'acceptance_criteria'
                },
                {
                    name: 'deliverable_tester',
                    mapping: 'deliverable_tester'
                },
                {
                    name: 'field'
                }
            ]
        }, cfg));
    }
});
new st_deliverables();